### ISSUE TITLE
VoiceReceiver Page

### ISSUE THREAD

**Issue by ismm0101** [discordjs/guide#1058] opened 2022-03-08 11:52 UTC
### Is your feature request related to a problem? Please describe.

it is not a problem

### Describe the solution you'd like

i would like to see more content on discordjs.guide such as "VoiceReceiver" class and the usage

**Comment by almostSouji** [comment] 2022-05-14 22:33
dupe of #990

**Closed by almostSouji** 2022-05-14 22:33 UTC
Labels: t: request, s: duplicate
