### ISSUE TITLE
canvas/image manipulation guide refers to `MessageAttachment`, should be `Attachment`

### ISSUE THREAD

**Issue by FluffierThanThou** [discordjs/guide#326] opened 2020-02-14 22:12 UTC
**Describe the bug**
canvas/image manipulation guide refers to `MessageAttachment` to create an image attachment from a buffer. The correct class to use appears to be `Attachment`.

**Screenshots**
![image](https://user-images.githubusercontent.com/18528306/74572302-2f3a1d00-4f7f-11ea-97e3-8140aa9aad42.png)
![image](https://user-images.githubusercontent.com/18528306/74572341-3eb96600-4f7f-11ea-8e50-ce52f38e50b5.png)

**Comment by tipakA** [comment] 2020-02-14 22:46
This most likely is not a bug in the guide.
On stable, there are both `MessageAttachment` and `Attachment`, but `MessageAttachment` is solely for attachments from *received* messages. To construct attachment you have to use `Attachment`.

On `master` however, those two were merged together, so you need to use `MessageAttachment` to create one.

Now, since you didn't note neither which guide version you're referring to, nor which version of discord.js do you use, i'm gonna post those two screenshots:
![image](https://user-images.githubusercontent.com/31581159/74574494-26981580-4f84-11ea-9c84-5ec7adacbe60.png)
![image](https://user-images.githubusercontent.com/31581159/74574501-2dbf2380-4f84-11ea-9769-e6eff9a6519d.png)

**Comment by almostSouji** [comment] 2020-02-15 12:17
thanks for the report, was fixed in #327

**Closed by almostSouji** 2020-02-15 12:17 UTC
Labels: bug
