### ISSUE TITLE
Update docs to suggest using dotenv

### ISSUE THREAD

**Issue by MikeyBeLike** [discordjs/guide#229] opened 2019-06-13 23:58 UTC
Currently the docs suggest using a [config.json](https://discordjs.guide/creating-your-bot/configuration-files.html#implementing-your-config-file) file for managing config variables.

Most people are probably going to be using a free hosting service such as heroku to host their node bots and generally these hosting services are configured via git & environment variables. I think it's a good practice to suggest to use [dotenv](https://github.com/motdotla/dotenv) as it has several benefits and very easy to configure out of the box, even for newbies.

I can make a PR to suggest this, but just wanted to make sure this fits inline with something you guys would be open to?

**Comment by Fyk0** [comment] 2019-06-14 00:43
Not necessary. There is nothing wrong with a JSON file for holding your credentials.

**Comment by Monbrey** [comment] 2019-06-14 01:03
I wouldn't replace it. Could be added as an alternative method.
Regardless of the method, I think it should also have a line that tells people to gitignore the file, or how to use `git update-index --assume-unchanged` to commit a default template version, but not to track changes to it

**Comment by appellation** [comment] 2019-06-14 01:18
I think that describing how to use environment variables would be very valuable for the guide, but I don't think it's worth replacing the existing JSON guide since that's still good information. I would be in favor of adding a new page describing how to use environment variables, be it with dotenv or other solutions.

**Comment by almostSouji** [comment] 2019-06-14 12:56
There are plans for this on the "Projects" as well as #100 
Since there are no news to it since January it's very open for contribution (ideas are welcome, if you want to try your hands on an implementation check out the [CONTRIBUTING.md](https://github.com/discordjs/guide/blob/master/CONTRIBUTING.md), we always welcome pull requests as well.)

There were conversations about placing DANGER elements on the config files page, which we did not do yet, as an in-depth page on token security and how to deal with them is planned (see above) but has escaped from our view lately, I fear.

If you want to PR a draft feel free, see it as an additional page on token security and environment variables, not a replacement, as appellation said already above.

*PS: In case anyone finds this issue i'll append some general guides for multiple platforms here and close this as dupe of #100.*

---

GitHub/-Lab: <https://git-scm.com/docs/gitignore>
Heroku: <https://devcenter.heroku.com/articles/config-vars>
Glitch: <https://support.glitch.com/t/how-do-i-set-environment-variables/3921>
Repl.it: <https://repl.it/site/docs/repls/secret-keys>
Node: <https://medium.freecodecamp.org/heres-how-you-can-actually-use-node-environment-variables-8fdf98f53a0a>
Invalidate your current token: <https://i.imgur.com/XtQsR9s.png> at <https://discordapp.com/developers/applications>

**Closed by almostSouji** 2019-06-14 12:56 UTC
