### ISSUE TITLE
Mongo db support/guide

### ISSUE THREAD

**Issue by BigglesDevs** [discordjs/guide#1438] opened 2023-03-30 05:24 UTC
### Is your feature request related to a problem? Please describe.

Frustrated how no clear or set guides about mongodb 

### Describe the solution you'd like

I would love to see a clear concise guide about connecting and where and what to add to your discord bot and how to properly use mongoose package and so on.

**Comment by monbrey** [comment] 2023-03-30 05:40
Duplicate of #1381 

We do not plan to cover more flavors of databases in the guide at this time.

**Closed** 2023-03-30 08:18 UTC
Labels: t: request
