### ISSUE TITLE
The cooldown code doesn't make my commands work anymore.

### ISSUE THREAD

**Issue by HLenin** [discordjs/guide#506] opened 2020-10-16 07:41 UTC
**Describe the bug**

As the title said, the cooldown code doesn't execute my commands. I did everything correctly actually, but it just doesn't work; I tried replacing some codes but it doesn't work and I don't know what to do.

**To Reproduce**

Device: Windows 10
Browser: Chrome
Version: ???

**Additional Notes**
All of my commands don't work, even though I only have one command with the `cooldown: 5` code. I think it doesn't execute the `try` part in my index file.

**Comment by Nyyaan** [comment] 2020-10-19 16:35
Can you show us your code?

**Comment by tipakA** [comment] 2020-11-03 10:34
The question still stands. Without you showing us your code, there is no way for us to even say if this is indeed a bug or not.

**Comment by Jonchu650** [comment] 2020-11-07 00:23
Please give us your code so we can help.

**Comment by almostSouji** [comment] 2020-11-07 08:18
Since people apparently started parroting asking for code i'm going to to close this until someone can reproduce. If you are experiencing issues with the usage of the library please visit the discord server instead.
https://discord.gg/bRCvFy9

**Closed by almostSouji** 2020-11-07 08:18 UTC
Labels: type: bug
