### ISSUE TITLE
Registering Slash Commands Example incongruent with folder structure

### ISSUE THREAD

**Issue by Mrfoofums** [discordjs/guide#1444] opened 2023-04-02 18:42 UTC
### Describe the bug

In order to register slash commands as shown in the example you need to properly traverse 'commands' folder structure.

The example you provide is

`const commands = [];
// Grab all the command files from the commands directory you created earlier
const commandsPath = path.join(__dirname, 'commands');
const commandFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.js'));

// Grab the SlashCommandBuilder#toJSON() output of each command's data for deployment
for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	commands.push(command.data.toJSON());
}`

But you need to utilize the previously shown traversal method in index.js

`const foldersPath = path.join(__dirname, 'commands');
const commandFolders = fs.readdirSync(foldersPath);

for (const folder of commandFolders) {
	const commandsPath = path.join(foldersPath, folder);
	const commandFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.js'));
	for (const file of commandFiles) {
		const filePath = path.join(commandsPath, file);
		const command = require(filePath);
		// Set a new item in the Collection with the key as the command name and the value as the exported module
		if ('data' in command && 'execute' in command) {
			client.commands.set(command.data.name, command);
		} else {
			console.log(`[WARNING] The command at ${filePath} is missing a required "data" or "execute" property.`);
		}
	}
}`

### To Reproduce

Follow the guide as shown

### Device (please complete the following information)

Mac

**Comment by bozgi** [comment] 2023-04-02 19:25
Also saw this

**Comment by Idris1401** [comment] 2023-04-02 20:02
duplicate of [#1140](https://github.com/discordjs/guide/issues/1440) ig

**Closed** 2023-04-02 20:04 UTC
Labels: type: bug, s: duplicate
