### ISSUE TITLE
A new loop for reading commands

### ISSUE THREAD

**Issue by Syjalo** [discordjs/guide#1379] opened 2022-12-18 17:13 UTC
### Is your feature request related to a problem? Please describe.

A new loop has recently been added for reading commands in `index.js`, but not in `deploy-commands.js`

![image](https://user-images.githubusercontent.com/62868468/208310573-06ad1f92-ef5e-4425-b0c0-f4bed891ac41.png)

`index.js`: https://discordjs.guide/creating-your-bot/command-handling.html#loading-command-files
`deploy-commands.js`: https://discordjs.guide/creating-your-bot/command-deployment.html#guild-commands

I suggest to add it in `deploy-commands.js` too.

### Describe the solution you'd like

Add a new loop

**Comment by Idris1401** [comment] 2022-12-18 18:37
I think it's a duplicate of [#1362](https://github.com/discordjs/guide/issues/1362)

**Comment by Syjalo** [comment] 2022-12-18 18:56
Not a duplicate. I'm about the warning in the loop, but not using fs.

**Comment by almostSouji** [comment] 2023-03-24 22:26
@monbrey is this covered/in scope of #1427 ?

**Closed** 2023-04-12 21:52 UTC
Labels: t: request
