### ISSUE TITLE
'Currency' is not defined

### ISSUE THREAD

**Issue by Ivette-Chan** [discordjs/guide#297] opened 2019-12-15 01:57 UTC
**Describe the bug**

I tried using the economy code and ran it, it said 'currency' is not defined for some reason. I looked over the code to see that it wasnt.

**Screenshots**

**Device (please complete the following information):**

**Comment by almostSouji** [comment] 2019-12-15 08:46
`currency` is defined in the boilerplate for the [currency system here](https://discordjs.guide/sequelize/currency.html#application-code).

As the introduction suction proposes this is a fill-in system, you fill in later code samples where they are marked in this boiler plate as `// [alpha]` to `// [lambda]` corresponding to the section heading.
If you follow this approach correctly there isn't really any way for the identifier `currency` to not be defined, as it is introduced at the very top.

The respective line in the code sample is: [here (L7)](https://github.com/discordjs/guide/blob/master/code-samples/sequelize/currency/app.js#L7)

I'd generally encourage you to read the [resulting code](https://discordjs.guide/sequelize/currency.html#resulting-code) of a section if you are unsure if you followed it correctly.

I'm going to close the issue, if the problem is in another part of the guide please provide the affected section. I'll close the issue for now, please let me know if I'm overlooking something.

**Closed by almostSouji** 2019-12-15 08:46 UTC
Labels: type: bug
